site_name: kenicのブログ
site_url: https://kenic.github.io/
site_description: misc misc misc and misc
plugins:
  - rss
  - search:
      lang:
        - en
        - ja
  - macros
  - awesome-pages
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Tokyo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kenic
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/kenic
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/iwatakenichi/
theme:
    name: material
    favicon: favicon.ico
    logo: kenic.png
    features:
      - content.action.edit
      - navigation.footer

